server:
  port: 8080

spring:
  application:
    name: tcc-api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://tcc-auth-service:8003
          predicates:
            - Path=/api/v1/auth/**

        - id: product-service
          uri: http://tcc-product-service:8001
          predicates:
            - Path=/api/v1/products/**

        - id: order-service
          uri: http://tcc-order-service:8002
          predicates:
            - Path=/api/v1/orders/**

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  gateway:
    key: ${GATEWAY_INTERNAL_KEY:verysecretkeythatshouldbechanged}
  jwt:
    secret: ${JWT_SECRET:I1bXzWRjypm4dfjCnXTuEkjX2kjPdA9oatgHHkyqLuK}
    issuer: ${JWT_ISSUER:http://tcc-auth-service:8003}
    audience: ${JWT_AUDIENCE:tcc-api-gateway}
    public-paths:
      - /actuator/health
      - /api/v1/auth/**
      - /public/**
